#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Jun  4 11:20:58 2019

@author: sebastiannyholm
"""
import matplotlib.pyplot as plt



data_raw = [[0.70,1.35,0.76,1.20,1.14,0.84,0.85,0.89,1.58,1.22],[1.33,0.86,0.81,0.96,1.38,1.35,1.49,1.70,1.90,1.35],[0.76,0.62,0.66,0.86,1.10,1.16,1.56,1.38,1.58,1.30]]
data_labels = ["Tobii", "2-Point", "5-Point"]

fig = plt.figure(1, figsize=(9,12))
ax_raw = fig.add_subplot(2,1,1)
ax_raw.boxplot(data_raw)
ax_raw.set_xticklabels(data_labels)

ax_raw.set_ylim(0,3)

fig.show()
